# Generated by Django 5.0.3 on 2025-03-02 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_email_verifiied_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_auth_required', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
